### PR TITLE
Updated Docker image

### LINKED ISSUE #122: merge HARDENS "classic" docker image with Simon's new docker image and publish to DockerHub
The NRC wants to ensure that a complete docker image is published for the project to guarantee reproducibility of the case study and report.  I suggest the shortest path to doing so is performing the work summarized in the title of this issue.  I'd like this done before our final presentation to the NRC, which is on 12 October.

### PR DESCRIPTION
**Pull request by SimplisticCode**
Updated Docker image to fetch and put the documentation enricher in the path.
I furthermore included a shell script to run the tool easily with some default parameters.

### CODE REVIEW

**Review by podhrmic — COMMENTED** [review]
Feel free to mention yourself in the README, since you are part of the team now.

**Review by podhrmic — APPROVED** [review]
Feel free to mention yourself in the README, since you are part of the team now.

**Review by podhrmic — CHANGES_REQUESTED** [review]
Feel free to mention yourself in the README, since you are part of the team now.

**Review by podhrmic — APPROVED** [review]

**Comment by podhrmic** [comment]
@kiniry Simon didn't sign his commits - do you want to just merge as is?

**Comment by podhrmic** [comment]
Closing in favor of #138

**Comment by kiniry** [comment]
We forgot to delete the branch.  I'll take care of it.

**Pull request closed without merging**
